/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Stitch AgriSense Premier Design System Tokens
        primary: "#004532",
        "primary-container": "#065f46",
        "on-primary": "#ffffff",
        "on-primary-container": "#8bd6b7",
        "primary-fixed": "#a6f2d1",
        "primary-fixed-dim": "#8bd6b6",
        "on-primary-fixed": "#002116",
        "on-primary-fixed-variant": "#00513b",
        secondary: "#904d00",
        "secondary-container": "#fe932c",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#663500",
        "secondary-fixed": "#ffdcc3",
        "secondary-fixed-dim": "#ffb77d",
        "on-secondary-fixed": "#2f1500",
        "on-secondary-fixed-variant": "#6e3900",
        tertiary: "#00462e",
        "tertiary-container": "#006041",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#50e0a4",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        surface: "#faf9f5",
        "surface-dim": "#dbdad6",
        "surface-bright": "#faf9f5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f4f0",
        "surface-container": "#efeeea",
        "surface-container-high": "#e9e8e4",
        "surface-container-highest": "#e3e2df",
        "surface-variant": "#e3e2df",
        "surface-tint": "#1b6b51",
        outline: "#6f7973",
        "outline-variant": "#bec9c2",
        "on-surface": "#1b1c1a",
        "on-surface-variant": "#3f4944",
        background: "#faf9f5",
        "on-background": "#1b1c1a",
        "inverse-surface": "#2f312e",
        "inverse-on-surface": "#f2f1ed",
        "inverse-primary": "#8bd6b6",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",

        // Backward compatibility mappings
        forest: {
          DEFAULT: "#004532",
          dark: "#003224",
          light: "#055c44",
        },
        emerald: {
          DEFAULT: "#065f46",
          dark: "#044734",
          light: "#0a8160",
        },
        mint: {
          DEFAULT: "#10b981",
          light: "#34d399",
          dark: "#059669",
        },
        amber: {
          DEFAULT: "#fe932c",
          dark: "#d97706",
          light: "#fbb066",
        },
        canvas: "#faf9f5",
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "system-ui", "sans-serif"],
        "display-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "title-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-sm": ["'Plus Jakarta Sans'", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.05em", fontWeight: "700" }],
        "label-md": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.04em", fontWeight: "600" }],
        "label-lg": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-sm": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "500" }],
        "body-md": ["1rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "body-lg": ["1.125rem", { lineHeight: "1.75rem", fontWeight: "400" }],
        "title-md": ["1rem", { lineHeight: "1.5rem", fontWeight: "600" }],
        "headline-sm": ["1.125rem", { lineHeight: "1.625rem", fontWeight: "600" }],
        "headline-md": ["1.375rem", { lineHeight: "1.875rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["2rem", { lineHeight: "2.5rem", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["1.625rem", { lineHeight: "2.125rem", letterSpacing: "-0.015em", fontWeight: "700" }],
        "display-lg": ["2.5rem", { lineHeight: "3rem", letterSpacing: "-0.03em", fontWeight: "800" }],
      },
      spacing: {
        "margin-desktop": "3rem",
        "margin-tablet": "2rem",
        "gutter-desktop": "2rem",
        "gutter-tablet": "1.5rem",
        "space-xl": "2.25rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
      },
    },
  },
  plugins: [],
};
