CREATE TABLE IF NOT EXISTS active_roles ("id" BIGSERIAL PRIMARY KEY, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "user_id" BIGINT NOT NULL, "role_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS advance_bookings ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "quantity_booked" DECIMAL(10,2) NOT NULL, "price_per_unit" DECIMAL(10,2) NOT NULL, "total_amount" DECIMAL(10,2) NOT NULL, "advance_payment_percent" INTEGER NOT NULL DEFAULT 20, "advance_payment_amount" DECIMAL(10,2) NOT NULL, "booking_date" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "expected_delivery_date" TIMESTAMP NOT NULL, "status" VARCHAR(50) NOT NULL DEFAULT 'pending', "quality_standards" TEXT DEFAULT NULL, "contract_terms" TEXT DEFAULT NULL, "listing_id" BIGINT NOT NULL, "buyer_id" BIGINT NOT NULL, "farmer_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS ai_usage_quota ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "date" DATE NOT NULL, "gps_enhanced_requests" INTEGER NOT NULL DEFAULT 0, "pincode_requests" INTEGER NOT NULL DEFAULT 0, "last_reset" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "quota_limit" INTEGER NOT NULL DEFAULT 20, "user_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS annual_strategies ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "year" INTEGER NOT NULL, "kharif_crop" VARCHAR(255) DEFAULT NULL, "kharif_profit_estimate" DECIMAL(12,2) DEFAULT NULL, "kharif_confidence_score" DECIMAL(3,2) DEFAULT NULL, "rabi_crop" VARCHAR(255) DEFAULT NULL, "rabi_profit_estimate" DECIMAL(12,2) DEFAULT NULL, "rabi_confidence_score" DECIMAL(3,2) DEFAULT NULL, "zaid_crop" VARCHAR(255) DEFAULT NULL, "zaid_profit_estimate" DECIMAL(12,2) DEFAULT NULL, "zaid_confidence_score" DECIMAL(3,2) DEFAULT NULL, "total_annual_profit" DECIMAL(12,2) DEFAULT NULL, "implementation_timeline" TEXT DEFAULT NULL, "alternative_options" TEXT DEFAULT NULL, "risk_mitigation" TEXT DEFAULT NULL, "bedrock_response" TEXT DEFAULT NULL, "status" VARCHAR(255) DEFAULT 'draft', "farm_id" BIGINT NOT NULL, "farmer_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS breeding_records ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "breeding_type" VARCHAR(50) NOT NULL, "breeding_date" DATE NOT NULL, "mate_breed" VARCHAR(255) DEFAULT NULL, "expected_delivery_date" DATE DEFAULT NULL, "actual_delivery_date" DATE DEFAULT NULL, "pregnancy_status" VARCHAR(50) NOT NULL DEFAULT 'pending', "number_of_offspring" INTEGER DEFAULT NULL, "breeding_cost" DECIMAL(10,2) DEFAULT NULL, "veterinarian_name" VARCHAR(255) DEFAULT NULL, "notes" TEXT DEFAULT NULL, "livestock_id" BIGINT NOT NULL, "farmer_id" BIGINT NOT NULL, "mate_id" BIGINT DEFAULT NULL);

CREATE TABLE IF NOT EXISTS buyer_interests ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "buyer_name" VARCHAR(255) NOT NULL, "buyer_phone" VARCHAR(255) NOT NULL, "buyer_email" VARCHAR(255) DEFAULT NULL, "buyer_type" VARCHAR(255) NOT NULL, "interested_quantity" INTEGER NOT NULL, "message" TEXT DEFAULT NULL, "status" VARCHAR(255) DEFAULT 'pending', "delivery_latitude" DECIMAL(10,8) DEFAULT NULL, "delivery_longitude" DECIMAL(11,8) DEFAULT NULL, "delivery_pincode" VARCHAR(10) DEFAULT NULL, "delivery_state" VARCHAR(100) DEFAULT NULL, "delivery_district" VARCHAR(100) DEFAULT NULL, "delivery_village" VARCHAR(100) DEFAULT NULL, "delivery_address_line" VARCHAR(255) DEFAULT NULL, "listing_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS crops ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "crop_name" VARCHAR(255) NOT NULL, "crop_variety" VARCHAR(255) DEFAULT NULL, "season" VARCHAR(255) NOT NULL, "planting_date" DATE NOT NULL, "expected_harvest_date" DATE NOT NULL, "area" DECIMAL(10,2) NOT NULL, "expected_yield" DECIMAL(12,2) DEFAULT NULL, "expected_profit" DECIMAL(12,2) DEFAULT NULL, "actual_yield" DECIMAL(12,2) DEFAULT NULL, "actual_profit" DECIMAL(12,2) DEFAULT NULL, "status" VARCHAR(255) DEFAULT 'planned', "parent_crop_id" BIGINT DEFAULT NULL, "crop_role" VARCHAR(20) DEFAULT 'main', "farm_plot_id" BIGINT NOT NULL, "strategy_id" BIGINT DEFAULT NULL);

CREATE TABLE IF NOT EXISTS crop_diagnoses ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "crop_id" BIGINT DEFAULT NULL, "farm_id" BIGINT DEFAULT NULL, "crop_name" VARCHAR(100) DEFAULT NULL, "state" VARCHAR(100) DEFAULT NULL, "district" VARCHAR(100) DEFAULT NULL, "disease_name" VARCHAR(255) DEFAULT NULL, "scientific_name" VARCHAR(255) DEFAULT NULL, "category" VARCHAR(30) DEFAULT NULL, "severity" VARCHAR(20) DEFAULT NULL, "urgency" VARCHAR(20) DEFAULT NULL, "confidence" DECIMAL(4,3) DEFAULT NULL, "language" VARCHAR(10) DEFAULT NULL, "model_used" VARCHAR(100) DEFAULT NULL, "safety_flags" INTEGER NOT NULL DEFAULT 0, "result" JSONB DEFAULT NULL, "user_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS crop_expenses ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "category" VARCHAR(255) NOT NULL, "amount" DECIMAL(12,2) NOT NULL, "description" TEXT DEFAULT NULL, "expense_date" DATE NOT NULL, "crop_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS crop_market_data ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "crop_name" VARCHAR(255) NOT NULL, "state" VARCHAR(255) NOT NULL, "district" VARCHAR(255) DEFAULT NULL, "price_per_kg" DECIMAL(10,2) NOT NULL, "date" DATE NOT NULL, "season" VARCHAR(255) NOT NULL, "yoy_growth" DECIMAL(5,2) DEFAULT NULL, "demand_level" VARCHAR(255) DEFAULT NULL);

CREATE TABLE IF NOT EXISTS crop_milestones ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "stage" VARCHAR(255) NOT NULL, "expected_start_date" DATE NOT NULL, "expected_end_date" DATE NOT NULL, "actual_start_date" DATE DEFAULT NULL, "actual_end_date" DATE DEFAULT NULL, "status" VARCHAR(255) DEFAULT 'pending', "progress_percentage" INTEGER DEFAULT 0, "recommendations" TEXT DEFAULT NULL, "notes" TEXT DEFAULT NULL, "alert_sent" SMALLINT DEFAULT 0, "crop_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS crop_profitability ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "crop_type" VARCHAR(100) NOT NULL, "variety" VARCHAR(200) DEFAULT NULL, "state" VARCHAR(100) NOT NULL, "district" VARCHAR(100) DEFAULT NULL, "year" INTEGER NOT NULL, "season" VARCHAR(50) DEFAULT NULL, "avg_profit_per_acre" DECIMAL(10,2) NOT NULL, "min_profit_per_acre" DECIMAL(10,2) DEFAULT NULL, "max_profit_per_acre" DECIMAL(10,2) DEFAULT NULL, "seed_cost" DECIMAL(10,2) DEFAULT NULL, "fertilizer_cost" DECIMAL(10,2) DEFAULT NULL, "pesticide_cost" DECIMAL(10,2) DEFAULT NULL, "labor_cost" DECIMAL(10,2) DEFAULT NULL, "irrigation_cost" DECIMAL(10,2) DEFAULT NULL, "equipment_cost" DECIMAL(10,2) DEFAULT NULL, "other_costs" DECIMAL(10,2) DEFAULT NULL, "total_investment_cost" DECIMAL(10,2) DEFAULT NULL, "avg_revenue_per_acre" DECIMAL(10,2) DEFAULT NULL, "roi_percentage" DECIMAL(5,2) DEFAULT NULL, "break_even_yield" DECIMAL(10,2) DEFAULT NULL, "profit_margin" DECIMAL(5,2) DEFAULT NULL, "risk_level" VARCHAR(20) DEFAULT NULL, "price_risk_score" DECIMAL(3,2) DEFAULT NULL, "yield_risk_score" DECIMAL(3,2) DEFAULT NULL, "market_demand" VARCHAR(20) DEFAULT NULL, "competition_level" VARCHAR(20) DEFAULT NULL, "data_source" VARCHAR(100) DEFAULT NULL, "sample_size" INTEGER DEFAULT NULL);

CREATE TABLE IF NOT EXISTS farms ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "name" VARCHAR(255) NOT NULL, "description" TEXT DEFAULT NULL, "location_state" VARCHAR(100) NOT NULL, "location_district" VARCHAR(100) NOT NULL, "location_block" VARCHAR(100) DEFAULT NULL, "location_village" VARCHAR(100) DEFAULT NULL, "latitude" DECIMAL(10,8) DEFAULT NULL, "longitude" DECIMAL(11,8) DEFAULT NULL, "total_area" DECIMAL(10,2) NOT NULL, "cultivable_area" DECIMAL(10,2) DEFAULT NULL, "area_unit" VARCHAR(20) DEFAULT NULL, "primary_soil_type" VARCHAR(50) DEFAULT NULL, "soil_ph" DECIMAL(3,1) DEFAULT NULL, "soil_characteristics" JSONB DEFAULT NULL, "irrigation_type" VARCHAR(50) DEFAULT NULL, "water_availability" VARCHAR(50) DEFAULT NULL, "previous_crops" TEXT[] DEFAULT NULL, "farming_experience_years" INTEGER DEFAULT NULL, "investment_capacity_per_acre" DECIMAL(10,2) DEFAULT NULL, "farm_profile_embedding" vector(512) DEFAULT NULL, "is_active" BOOLEAN DEFAULT NULL DEFAULT true, "is_verified" BOOLEAN DEFAULT NULL DEFAULT false, "nitrogen" DECIMAL(10,2) DEFAULT NULL, "phosphorus" DECIMAL(10,2) DEFAULT NULL, "potassium" DECIMAL(10,2) DEFAULT NULL, "ph_level" DECIMAL(4,2) DEFAULT NULL, "organic_carbon" DECIMAL(5,2) DEFAULT NULL, "electrical_conductivity" DECIMAL(5,2) DEFAULT NULL, "sulfur" DECIMAL(10,2) DEFAULT NULL, "zinc" DECIMAL(10,2) DEFAULT NULL, "iron" DECIMAL(10,2) DEFAULT NULL, "boron" DECIMAL(10,2) DEFAULT NULL, "copper" DECIMAL(10,2) DEFAULT NULL, "manganese" DECIMAL(10,2) DEFAULT NULL, "soil_depth_class" VARCHAR(50) DEFAULT NULL, "slope_class" VARCHAR(50) DEFAULT NULL, "erosion_class" VARCHAR(50) DEFAULT NULL, "soil_texture_class" VARCHAR(50) DEFAULT NULL, "land_capability_class" VARCHAR(10) DEFAULT NULL, "land_irrigability_class" VARCHAR(10) DEFAULT NULL, "hydrological_soil_group" VARCHAR(10) DEFAULT NULL, "shc_data_source" VARCHAR(100) DEFAULT NULL, "shc_fetched_at" TIMESTAMP DEFAULT NULL, "shc_partial_data" BOOLEAN DEFAULT NULL DEFAULT false, "shc_unavailable_styles" TEXT[] DEFAULT NULL, "user_id" BIGINT NOT NULL, "owner_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS farm_plots ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "plot_name" VARCHAR(255) NOT NULL, "area" DECIMAL(10,2) NOT NULL, "soil_type" VARCHAR(255) NOT NULL, "irrigation_type" VARCHAR(255) NOT NULL, "state" VARCHAR(255) NOT NULL, "district" VARCHAR(255) NOT NULL, "previous_crops" VARCHAR(255) DEFAULT NULL, "investment_capacity" DECIMAL(12,2) DEFAULT NULL, "nitrogen" DECIMAL(10,2) DEFAULT NULL, "phosphorus" DECIMAL(10,2) DEFAULT NULL, "potassium" DECIMAL(10,2) DEFAULT NULL, "ph_level" DECIMAL(4,2) DEFAULT NULL, "organic_carbon" DECIMAL(5,2) DEFAULT NULL, "electrical_conductivity" DECIMAL(5,2) DEFAULT NULL, "sulfur" DECIMAL(10,2) DEFAULT NULL, "zinc" DECIMAL(10,2) DEFAULT NULL, "iron" DECIMAL(10,2) DEFAULT NULL, "boron" DECIMAL(10,2) DEFAULT NULL, "farm_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS fertilizer_applications ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "application_date" DATE NOT NULL, "fertilizer_type" VARCHAR(100) NOT NULL, "category" VARCHAR(50) NOT NULL, "quantity_kg" DECIMAL(10,2) NOT NULL, "quantity_per_hectare" DECIMAL(10,2) DEFAULT NULL, "area_applied_hectares" DECIMAL(10,2) DEFAULT NULL, "nitrogen_kg" DECIMAL(10,2) DEFAULT NULL, "phosphorus_kg" DECIMAL(10,2) DEFAULT NULL, "potassium_kg" DECIMAL(10,2) DEFAULT NULL, "cost_total" DECIMAL(10,2) DEFAULT NULL, "cost_per_kg" DECIMAL(10,2) DEFAULT NULL, "cost_per_hectare" DECIMAL(10,2) DEFAULT NULL, "application_method" VARCHAR(255) DEFAULT NULL, "growth_stage" VARCHAR(100) DEFAULT NULL, "days_after_planting" BIGINT DEFAULT NULL, "effectiveness_score" DECIMAL(5,2) DEFAULT NULL, "soil_response_notes" TEXT DEFAULT NULL, "weather_conditions" VARCHAR(255) DEFAULT NULL, "temperature_celsius" DECIMAL(5,2) DEFAULT NULL, "rainfall_mm_24h" DECIMAL(6,2) DEFAULT NULL, "recommended_by" VARCHAR(255) DEFAULT NULL, "recommendation_id" VARCHAR(255) DEFAULT NULL, "notes" TEXT DEFAULT NULL, "farm_id" BIGINT NOT NULL, "plot_id" BIGINT DEFAULT NULL, "crop_id" BIGINT DEFAULT NULL, "soil_test_before_id" BIGINT DEFAULT NULL, "soil_test_after_id" BIGINT DEFAULT NULL);

CREATE TABLE IF NOT EXISTS historical_yields ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "crop_type" VARCHAR(100) NOT NULL, "variety" VARCHAR(200) DEFAULT NULL, "state" VARCHAR(100) NOT NULL, "district" VARCHAR(100) DEFAULT NULL, "block" VARCHAR(100) DEFAULT NULL, "year" INTEGER NOT NULL, "season" VARCHAR(50) DEFAULT NULL, "avg_yield_per_acre" DECIMAL(10,2) NOT NULL, "min_yield" DECIMAL(10,2) DEFAULT NULL, "max_yield" DECIMAL(10,2) DEFAULT NULL, "success_rate" DECIMAL(5,2) DEFAULT NULL, "farmer_count" INTEGER DEFAULT NULL, "total_area_cultivated" DECIMAL(12,2) DEFAULT NULL, "soil_types" JSONB DEFAULT NULL, "irrigation_methods" JSONB DEFAULT NULL, "avg_rainfall" DECIMAL(8,2) DEFAULT NULL, "avg_temperature" DECIMAL(5,2) DEFAULT NULL, "quality_distribution" JSONB DEFAULT NULL, "avg_quality_grade" VARCHAR(10) DEFAULT NULL, "data_source" VARCHAR(100) DEFAULT NULL, "data_quality_score" DECIMAL(3,2) DEFAULT NULL);

CREATE TABLE IF NOT EXISTS livestock ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "species" VARCHAR(255) NOT NULL, "breed" VARCHAR(255) NOT NULL, "name" VARCHAR(100) DEFAULT NULL, "quantity" INTEGER NOT NULL DEFAULT 1, "purchase_price" DECIMAL(12,2) NOT NULL, "purchase_date" DATE NOT NULL, "purpose" VARCHAR(255) NOT NULL, "expected_roi" DECIMAL(12,2) DEFAULT NULL, "break_even_date" DATE DEFAULT NULL, "status" VARCHAR(255) DEFAULT 'active', "latitude" DECIMAL(10,8) DEFAULT NULL, "longitude" DECIMAL(11,8) DEFAULT NULL, "pincode" VARCHAR(10) DEFAULT NULL, "state" VARCHAR(100) DEFAULT NULL, "district" VARCHAR(100) DEFAULT NULL, "village" VARCHAR(100) DEFAULT NULL, "address_line" VARCHAR(255) DEFAULT NULL, "farm_id" BIGINT NOT NULL, "farmer_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS livestock_health_records ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "record_type" VARCHAR(255) NOT NULL, "record_date" DATE NOT NULL, "description" TEXT NOT NULL, "veterinarian_name" VARCHAR(255) DEFAULT NULL, "cost" DECIMAL(10,2) DEFAULT NULL, "next_due_date" DATE DEFAULT NULL, "notes" TEXT DEFAULT NULL, "livestock_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS livestock_listings ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "title" VARCHAR(255) NOT NULL, "description" TEXT DEFAULT NULL, "species" VARCHAR(100) NOT NULL, "breed" VARCHAR(255) NOT NULL, "age_years" INTEGER DEFAULT NULL, "age_months" INTEGER DEFAULT NULL, "gender" VARCHAR(50) NOT NULL, "quantity" INTEGER NOT NULL DEFAULT 1, "purpose" VARCHAR(100) NOT NULL, "price" DECIMAL(12,2) NOT NULL, "price_negotiable" SMALLINT DEFAULT 1, "weight_kg" DECIMAL(10,2) DEFAULT NULL, "health_status" VARCHAR(100) DEFAULT 'healthy', "vaccination_status" VARCHAR(100) DEFAULT NULL, "last_vaccination_date" DATE DEFAULT NULL, "milk_production_liters" DECIMAL(10,2) DEFAULT NULL, "breeding_certified" SMALLINT DEFAULT 0, "breeding_certification_number" VARCHAR(255) DEFAULT NULL, "genetic_lineage" TEXT DEFAULT NULL, "photos" TEXT DEFAULT NULL, "videos" TEXT DEFAULT NULL, "location_state" VARCHAR(100) NOT NULL, "location_district" VARCHAR(100) NOT NULL, "location_village" VARCHAR(100) DEFAULT NULL, "latitude" DECIMAL(10,8) DEFAULT NULL, "longitude" DECIMAL(11,8) DEFAULT NULL, "pincode" VARCHAR(10) DEFAULT NULL, "address_line" VARCHAR(255) DEFAULT NULL, "farmer_contact_phone" VARCHAR(20) DEFAULT NULL, "farmer_contact_email" VARCHAR(255) DEFAULT NULL, "status" VARCHAR(50) DEFAULT 'active', "views_count" INTEGER DEFAULT 0, "interest_count" INTEGER DEFAULT 0, "inquiry_count" INTEGER DEFAULT 0, "featured" SMALLINT DEFAULT 0, "featured_until" TIMESTAMP DEFAULT NULL, "livestock_id" BIGINT NOT NULL, "farmer_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS livestock_marketplace_listings ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "listing_type" VARCHAR(255) NOT NULL, "asking_price" DECIMAL(12,2) NOT NULL, "current_age_months" INTEGER NOT NULL, "current_weight_kg" DECIMAL(10,2) DEFAULT NULL, "milk_production_liters_per_day" DECIMAL(10,2) DEFAULT NULL, "breeding_history" TEXT DEFAULT NULL, "health_status" VARCHAR(255) DEFAULT 'excellent', "vaccination_status" VARCHAR(255) DEFAULT 'up_to_date', "total_investment" DECIMAL(12,2) NOT NULL, "total_revenue" DECIMAL(12,2) DEFAULT 0, "current_roi_percentage" DECIMAL(10,2) DEFAULT NULL, "break_even_achieved" SMALLINT DEFAULT 0, "break_even_date" DATE DEFAULT NULL, "projected_annual_profit" DECIMAL(12,2) DEFAULT NULL, "location_state" VARCHAR(255) NOT NULL, "location_district" VARCHAR(255) NOT NULL, "farmer_contact_phone" VARCHAR(255) NOT NULL, "farmer_contact_email" VARCHAR(255) DEFAULT NULL, "listing_status" VARCHAR(255) DEFAULT 'active', "views_count" INTEGER DEFAULT 0, "bedrock_analysis" TEXT DEFAULT NULL, "livestock_id" BIGINT NOT NULL, "farmer_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS livestock_roi_predictions ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "prediction_date" DATE NOT NULL, "prediction_type" VARCHAR(50) DEFAULT NULL, "species" VARCHAR(50) NOT NULL, "breed" VARCHAR(100) NOT NULL, "age_months" INTEGER DEFAULT NULL, "purpose" VARCHAR(50) NOT NULL, "purchase_price" DECIMAL(10,2) NOT NULL, "initial_setup_cost" DECIMAL(10,2) DEFAULT NULL, "total_initial_investment" DECIMAL(10,2) NOT NULL, "monthly_feed_cost" DECIMAL(10,2) NOT NULL, "monthly_healthcare_cost" DECIMAL(10,2) DEFAULT NULL, "monthly_labor_cost" DECIMAL(10,2) DEFAULT NULL, "monthly_other_costs" DECIMAL(10,2) DEFAULT NULL, "total_monthly_cost" DECIMAL(10,2) NOT NULL, "monthly_milk_revenue" DECIMAL(10,2) DEFAULT NULL, "monthly_egg_revenue" DECIMAL(10,2) DEFAULT NULL, "monthly_wool_revenue" DECIMAL(10,2) DEFAULT NULL, "monthly_manure_revenue" DECIMAL(10,2) DEFAULT NULL, "total_monthly_revenue" DECIMAL(10,2) DEFAULT NULL, "offspring_revenue_per_year" DECIMAL(10,2) DEFAULT NULL, "expected_sale_value" DECIMAL(10,2) DEFAULT NULL, "expected_productive_years" INTEGER DEFAULT NULL, "break_even_months" INTEGER NOT NULL, "break_even_date" DATE DEFAULT NULL, "roi_1_year" DECIMAL(10,2) DEFAULT NULL, "roi_2_year" DECIMAL(10,2) DEFAULT NULL, "roi_5_year" DECIMAL(10,2) DEFAULT NULL, "roi_percentage_1_year" DECIMAL(5,2) DEFAULT NULL, "roi_percentage_2_year" DECIMAL(5,2) DEFAULT NULL, "roi_percentage_5_year" DECIMAL(5,2) DEFAULT NULL, "monthly_net_profit" DECIMAL(10,2) DEFAULT NULL, "annual_net_profit" DECIMAL(10,2) DEFAULT NULL, "lifetime_net_profit" DECIMAL(10,2) DEFAULT NULL, "comparison_with_alternatives" JSONB DEFAULT NULL, "market_price_trends" JSONB DEFAULT NULL, "risk_level" VARCHAR(20) DEFAULT NULL, "risk_factors" JSONB DEFAULT NULL, "mortality_risk" DECIMAL(5,2) DEFAULT NULL, "disease_risk" DECIMAL(5,2) DEFAULT NULL, "market_risk" DECIMAL(5,2) DEFAULT NULL, "confidence_score" DECIMAL(3,2) DEFAULT NULL, "key_assumptions" JSONB DEFAULT NULL, "sensitivity_analysis" JSONB DEFAULT NULL, "recommendation" TEXT DEFAULT NULL, "optimization_suggestions" JSONB DEFAULT NULL, "market_data_source" VARCHAR(100) DEFAULT NULL, "breed_performance_data_source" VARCHAR(100) DEFAULT NULL, "animal_id" BIGINT DEFAULT NULL, "user_id" BIGINT DEFAULT NULL);

CREATE TABLE IF NOT EXISTS livestock_transactions ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "transaction_type" VARCHAR(50) NOT NULL, "quantity" INTEGER NOT NULL DEFAULT 1, "agreed_price" DECIMAL(12,2) NOT NULL, "status" VARCHAR(50) DEFAULT 'inquiry', "buyer_message" TEXT DEFAULT NULL, "seller_response" TEXT DEFAULT NULL, "buyer_contact_phone" VARCHAR(20) DEFAULT NULL, "buyer_contact_email" VARCHAR(255) DEFAULT NULL, "delivery_required" SMALLINT DEFAULT 0, "delivery_address" TEXT DEFAULT NULL, "delivery_latitude" DECIMAL(10,8) DEFAULT NULL, "delivery_longitude" DECIMAL(11,8) DEFAULT NULL, "health_guarantee_days" INTEGER DEFAULT 7, "health_guarantee_expires" TIMESTAMP DEFAULT NULL, "completed_at" TIMESTAMP DEFAULT NULL, "cancelled_at" TIMESTAMP DEFAULT NULL, "cancellation_reason" TEXT DEFAULT NULL, "notes" TEXT DEFAULT NULL, "listing_id" BIGINT NOT NULL, "seller_id" BIGINT NOT NULL, "buyer_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS market_prices ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "item_type" VARCHAR(50) NOT NULL, "item_name" VARCHAR(255) NOT NULL, "variety" VARCHAR(255) DEFAULT NULL, "price_per_unit" DECIMAL(10,2) NOT NULL, "quantity" DECIMAL(10,2) NOT NULL, "total_value" DECIMAL(12,2) NOT NULL, "quality_grade" VARCHAR(10) DEFAULT NULL, "quality_premium_percent" DECIMAL(5,2) DEFAULT NULL, "state" VARCHAR(100) NOT NULL, "district" VARCHAR(100) NOT NULL, "transaction_date" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "season" VARCHAR(50) DEFAULT NULL, "source" VARCHAR(50) NOT NULL, "listing_id" BIGINT DEFAULT NULL, "booking_id" BIGINT DEFAULT NULL, "transaction_id" BIGINT DEFAULT NULL);

CREATE TABLE IF NOT EXISTS marketplace_listings ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "crop_type" VARCHAR(255) NOT NULL, "crop_variety" VARCHAR(255) DEFAULT NULL, "expected_harvest_date" DATE NOT NULL, "estimated_quantity" INTEGER NOT NULL, "available_quantity" INTEGER DEFAULT NULL, "quality_grade" VARCHAR(255) DEFAULT NULL, "location_state" VARCHAR(255) NOT NULL, "location_district" VARCHAR(255) NOT NULL, "farmer_contact_phone" VARCHAR(255) DEFAULT NULL, "farmer_contact_email" VARCHAR(255) DEFAULT NULL, "status" VARCHAR(255) DEFAULT 'active', "delivery_latitude" DECIMAL(10,8) DEFAULT NULL, "delivery_longitude" DECIMAL(11,8) DEFAULT NULL, "delivery_pincode" VARCHAR(10) DEFAULT NULL, "delivery_village" VARCHAR(100) DEFAULT NULL, "delivery_address_line" VARCHAR(255) DEFAULT NULL, "embedding" vector(384) DEFAULT NULL, "embedding_cache_key" VARCHAR(255) DEFAULT NULL, "price_per_unit" DECIMAL(10,2) DEFAULT NULL, "farm_id" BIGINT NOT NULL, "farmer_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS msp_rates ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "crop_name" VARCHAR(255) NOT NULL, "year" INTEGER NOT NULL, "season" VARCHAR(50) NOT NULL, "msp_per_quintal" DECIMAL(10,2) NOT NULL, "msp_per_kg" DECIMAL(10,2) DEFAULT NULL, "increase_over_previous" DECIMAL(5,2) DEFAULT NULL, "cost_of_production" DECIMAL(10,2) DEFAULT NULL, "return_over_cost_percent" DECIMAL(5,2) DEFAULT NULL, "source" VARCHAR(100) DEFAULT NULL);

CREATE TABLE IF NOT EXISTS ndap_downloaded_files ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "file_name" VARCHAR(255) NOT NULL, "file_hash" VARCHAR(64) NOT NULL UNIQUE, "file_content" BYTEA NOT NULL);

CREATE TABLE IF NOT EXISTS ndap_ingestion_runs ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "file_name" VARCHAR(255) NOT NULL, "file_hash" VARCHAR(64) NOT NULL UNIQUE, "started_at" TIMESTAMP NOT NULL, "completed_at" TIMESTAMP DEFAULT NULL, "status" VARCHAR(20) NOT NULL, "records_ingested" INTEGER DEFAULT NULL DEFAULT 0, "error_message" TEXT DEFAULT NULL);

CREATE TABLE IF NOT EXISTS offspring ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "birth_date" DATE NOT NULL, "gender" VARCHAR(20) DEFAULT NULL, "birth_weight" DECIMAL(10,2) DEFAULT NULL, "health_status" VARCHAR(50) NOT NULL DEFAULT 'healthy', "current_weight" DECIMAL(10,2) DEFAULT NULL, "growth_rate" DECIMAL(10,2) DEFAULT NULL, "weaning_date" DATE DEFAULT NULL, "sale_date" DATE DEFAULT NULL, "sale_price" DECIMAL(12,2) DEFAULT NULL, "notes" TEXT DEFAULT NULL, "breeding_record_id" BIGINT NOT NULL, "livestock_id" BIGINT DEFAULT NULL, "farmer_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS opportunity_costs ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "location_state" VARCHAR(100) NOT NULL, "location_district" VARCHAR(100) DEFAULT NULL, "primary_crop" VARCHAR(100) NOT NULL, "alternative_crop" VARCHAR(100) NOT NULL, "season" VARCHAR(50) DEFAULT NULL, "year" INTEGER DEFAULT NULL, "primary_crop_profit" DECIMAL(10,2) NOT NULL, "alternative_crop_profit" DECIMAL(10,2) NOT NULL, "profit_difference" DECIMAL(10,2) NOT NULL, "primary_crop_investment" DECIMAL(10,2) DEFAULT NULL, "alternative_crop_investment" DECIMAL(10,2) DEFAULT NULL, "investment_difference" DECIMAL(10,2) DEFAULT NULL, "primary_crop_roi" DECIMAL(5,2) DEFAULT NULL, "alternative_crop_roi" DECIMAL(5,2) DEFAULT NULL, "roi_difference" DECIMAL(5,2) DEFAULT NULL, "primary_crop_risk" VARCHAR(20) DEFAULT NULL, "alternative_crop_risk" VARCHAR(20) DEFAULT NULL, "risk_factor" DECIMAL(3,2) DEFAULT NULL, "primary_crop_demand" VARCHAR(20) DEFAULT NULL, "alternative_crop_demand" VARCHAR(20) DEFAULT NULL, "market_stability_comparison" TEXT DEFAULT NULL, "recommended_choice" VARCHAR(100) DEFAULT NULL, "recommendation_confidence" DECIMAL(3,2) DEFAULT NULL, "recommendation_reasoning" TEXT DEFAULT NULL, "soil_suitability_comparison" JSONB DEFAULT NULL, "water_requirement_comparison" JSONB DEFAULT NULL, "labor_requirement_comparison" JSONB DEFAULT NULL);

CREATE TABLE IF NOT EXISTS payment_milestones ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "milestone_type" VARCHAR(50) NOT NULL, "amount" DECIMAL(10,2) NOT NULL, "due_date" TIMESTAMP NOT NULL, "paid_date" TIMESTAMP DEFAULT NULL, "status" VARCHAR(50) NOT NULL DEFAULT 'pending', "payment_method" VARCHAR(100) DEFAULT NULL, "transaction_id" VARCHAR(255) DEFAULT NULL, "booking_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS pest_disease_alerts ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "pest_disease_name" VARCHAR(255) NOT NULL, "alert_type" VARCHAR(50) NOT NULL, "severity" VARCHAR(50) NOT NULL, "description" TEXT NOT NULL, "crop_stage" VARCHAR(100) NOT NULL, "weather_conditions" TEXT DEFAULT NULL, "organic_recommendations" TEXT DEFAULT NULL, "chemical_recommendations" TEXT DEFAULT NULL, "prevention_measures" TEXT DEFAULT NULL, "timing_instructions" TEXT DEFAULT NULL, "notification_sent" SMALLINT DEFAULT 0, "notification_sent_at" TIMESTAMP DEFAULT NULL, "is_resolved" SMALLINT DEFAULT 0, "resolved_at" TIMESTAMP DEFAULT NULL, "crop_id" BIGINT NOT NULL, "farm_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS pest_disease_data ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "name" VARCHAR(255) NOT NULL UNIQUE, "type" VARCHAR(50) NOT NULL, "scientific_name" VARCHAR(255) DEFAULT NULL, "description" TEXT NOT NULL, "affected_crops" TEXT DEFAULT NULL, "risk_stages" TEXT DEFAULT NULL, "temperature_min" DECIMAL(5,2) DEFAULT NULL, "temperature_max" DECIMAL(5,2) DEFAULT NULL, "humidity_min" INTEGER DEFAULT NULL, "humidity_max" INTEGER DEFAULT NULL, "rainfall_min" DECIMAL(6,2) DEFAULT NULL, "severity" VARCHAR(50) NOT NULL, "organic_treatments" TEXT DEFAULT NULL, "chemical_treatments" TEXT DEFAULT NULL, "prevention_measures" TEXT DEFAULT NULL, "timing_instructions" TEXT DEFAULT NULL, "data_source" VARCHAR(255) DEFAULT NULL, "last_updated" TIMESTAMP DEFAULT NULL);

CREATE TABLE IF NOT EXISTS price_predictions ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "item_type" VARCHAR(50) NOT NULL, "item_name" VARCHAR(255) NOT NULL, "variety" VARCHAR(255) DEFAULT NULL, "state" VARCHAR(100) NOT NULL, "district" VARCHAR(100) DEFAULT NULL, "prediction_date" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "target_date" DATE NOT NULL, "predicted_price" DECIMAL(10,2) NOT NULL, "confidence_score" DECIMAL(3,2) NOT NULL, "price_range_min" DECIMAL(10,2) DEFAULT NULL, "price_range_max" DECIMAL(10,2) DEFAULT NULL, "trend" VARCHAR(20) DEFAULT NULL, "demand_forecast" VARCHAR(20) DEFAULT NULL, "supply_forecast" VARCHAR(20) DEFAULT NULL, "season" VARCHAR(50) DEFAULT NULL, "model_version" VARCHAR(50) DEFAULT NULL, "factors" TEXT DEFAULT NULL);

CREATE TABLE IF NOT EXISTS push_subscriptions ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "user_id" BIGINT NOT NULL, "endpoint" TEXT NOT NULL, "p256dh" VARCHAR(255) NOT NULL, "auth" VARCHAR(255) NOT NULL, "user_agent" VARCHAR(512) DEFAULT NULL);

CREATE TABLE IF NOT EXISTS quality_verifications ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "verification_date" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "verifier_type" VARCHAR(50) NOT NULL, "quality_grade" VARCHAR(10) NOT NULL, "quality_metrics" TEXT DEFAULT NULL, "photos" TEXT DEFAULT NULL, "passed" SMALLINT NOT NULL DEFAULT 0, "notes" TEXT DEFAULT NULL, "booking_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS roles ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "name" VARCHAR(255) NOT NULL);

CREATE TABLE IF NOT EXISTS satellite_observations ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "scene_id" VARCHAR(120) NOT NULL, "observed_on" DATE NOT NULL, "source" VARCHAR(50) NOT NULL DEFAULT 'sentinel-2-l2a', "ndvi" DECIMAL(5,3) DEFAULT NULL, "ndmi" DECIMAL(5,3) DEFAULT NULL, "ndre" DECIMAL(5,3) DEFAULT NULL, "clear_pct" DECIMAL(5,1) DEFAULT NULL, "pixels" INTEGER DEFAULT NULL, "state" VARCHAR(100) DEFAULT NULL, "district" VARCHAR(100) DEFAULT NULL, "farm_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS seasonal_trends ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "crop_type" VARCHAR(100) NOT NULL, "state" VARCHAR(100) NOT NULL, "district" VARCHAR(100) DEFAULT NULL, "planting_season" VARCHAR(50) NOT NULL, "harvest_season" VARCHAR(50) DEFAULT NULL, "optimal_planting_start" DATE DEFAULT NULL, "optimal_planting_end" DATE DEFAULT NULL, "optimal_harvest_start" DATE DEFAULT NULL, "optimal_harvest_end" DATE DEFAULT NULL, "avg_growth_duration_days" INTEGER DEFAULT NULL, "price_trend_yoy" DECIMAL(5,2) DEFAULT NULL, "demand_trend_yoy" DECIMAL(5,2) DEFAULT NULL, "yield_trend_yoy" DECIMAL(5,2) DEFAULT NULL, "weather_suitability_score" DECIMAL(3,2) DEFAULT NULL, "pest_disease_risk" VARCHAR(20) DEFAULT NULL, "market_timing_score" DECIMAL(3,2) DEFAULT NULL, "avg_success_rate" DECIMAL(5,2) DEFAULT NULL, "farmer_adoption_rate" DECIMAL(5,2) DEFAULT NULL, "recommended_varieties" JSONB DEFAULT NULL, "companion_crops" JSONB DEFAULT NULL, "rotation_recommendations" JSONB DEFAULT NULL, "analysis_start_year" INTEGER DEFAULT NULL, "analysis_end_year" INTEGER DEFAULT NULL, "years_of_data" INTEGER DEFAULT NULL);

CREATE TABLE IF NOT EXISTS services ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "category" VARCHAR(50) NOT NULL, "name" VARCHAR(255) NOT NULL, "organisation" VARCHAR(255) DEFAULT NULL, "description" TEXT DEFAULT NULL, "phone" VARCHAR(20) NOT NULL, "whatsapp" VARCHAR(20) DEFAULT NULL, "email" VARCHAR(255) DEFAULT NULL, "location_state" VARCHAR(100) DEFAULT NULL, "location_district" VARCHAR(100) DEFAULT NULL, "address" TEXT DEFAULT NULL, "languages" VARCHAR(100) DEFAULT NULL, "available_now" SMALLINT NOT NULL DEFAULT 1, "verified" SMALLINT NOT NULL DEFAULT 0, "is_active" SMALLINT NOT NULL DEFAULT 1, "added_by_user_id" BIGINT DEFAULT NULL, "user_id" BIGINT DEFAULT NULL);

CREATE TABLE IF NOT EXISTS shc_state_district_codes ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "state_name" VARCHAR(100) NOT NULL, "state_code" INTEGER NOT NULL, "district_name" VARCHAR(100) NOT NULL, "district_code" INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS slusi_ingestion_runs ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "started_at" TIMESTAMP NOT NULL, "completed_at" TIMESTAMP DEFAULT NULL, "status" VARCHAR(20) NOT NULL, "lcc_records_ingested" INTEGER DEFAULT NULL DEFAULT 0, "maps_ingested" INTEGER DEFAULT NULL DEFAULT 0, "error_message" TEXT DEFAULT NULL);

CREATE TABLE IF NOT EXISTS slusi_lcc_reports ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "state" VARCHAR(100) NOT NULL, "district" VARCHAR(100) NOT NULL, "report_no" VARCHAR(50) NOT NULL, "year" INTEGER DEFAULT NULL, "total_area_ha" DECIMAL(14,2) DEFAULT NULL, "lcc_class_i" DECIMAL(14,2) DEFAULT NULL, "lcc_class_ii" DECIMAL(14,2) DEFAULT NULL, "lcc_class_iii" DECIMAL(14,2) DEFAULT NULL, "lcc_class_iv" DECIMAL(14,2) DEFAULT NULL, "lcc_class_v" DECIMAL(14,2) DEFAULT NULL, "lcc_class_vi" DECIMAL(14,2) DEFAULT NULL, "lcc_class_vii" DECIMAL(14,2) DEFAULT NULL, "lcc_class_viii" DECIMAL(14,2) DEFAULT NULL, "forest_area" DECIMAL(14,2) DEFAULT NULL, "miscellaneous_area" DECIMAL(14,2) DEFAULT NULL, "spatial_available" BOOLEAN DEFAULT NULL DEFAULT false, "non_spatial_available" BOOLEAN DEFAULT NULL DEFAULT false, "ingested_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS slusi_microwatershed_maps ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "state" VARCHAR(100) NOT NULL UNIQUE, "map_data" BYTEA NOT NULL, "file_size_bytes" INTEGER DEFAULT NULL, "ingested_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS soil_amendments ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "amendment_date" DATE NOT NULL, "amendment_type" VARCHAR(100) NOT NULL, "amendment_name" VARCHAR(200) DEFAULT NULL, "primary_purpose" VARCHAR(100) DEFAULT NULL, "target_improvement" JSONB DEFAULT NULL, "quantity" DECIMAL(10,2) NOT NULL, "unit" VARCHAR(20) NOT NULL, "quantity_per_acre" DECIMAL(10,2) DEFAULT NULL, "application_method" VARCHAR(100) DEFAULT NULL, "incorporation_depth" DECIMAL(5,2) DEFAULT NULL, "cost" DECIMAL(10,2) DEFAULT NULL, "cost_per_acre" DECIMAL(10,2) DEFAULT NULL, "organic_matter_content" DECIMAL(5,2) DEFAULT NULL, "nutrient_content" JSONB DEFAULT NULL, "carbon_nitrogen_ratio" DECIMAL(5,2) DEFAULT NULL, "current_ph" DECIMAL(3,1) DEFAULT NULL, "target_ph" DECIMAL(3,1) DEFAULT NULL, "expected_ph_change" DECIMAL(3,1) DEFAULT NULL, "days_before_planting" INTEGER DEFAULT NULL, "soil_moisture_at_application" VARCHAR(50) DEFAULT NULL, "weather_conditions" JSONB DEFAULT NULL, "expected_benefits" JSONB DEFAULT NULL, "expected_duration_months" INTEGER DEFAULT NULL, "actual_benefits" JSONB DEFAULT NULL, "effectiveness_rating" INTEGER DEFAULT NULL, "recommendation_source" VARCHAR(100) DEFAULT NULL, "recommended_by" VARCHAR(255) DEFAULT NULL, "notes" TEXT DEFAULT NULL, "plot_id" BIGINT NOT NULL, "follow_up_soil_test_id" BIGINT DEFAULT NULL);

CREATE TABLE IF NOT EXISTS soil_moisture_data ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "state" VARCHAR(100) NOT NULL, "district" VARCHAR(100) NOT NULL, "date" DATE NOT NULL, "year" INTEGER NOT NULL, "month" VARCHAR(2) NOT NULL, "moisture_level" DECIMAL(10,4) NOT NULL, "agency_name" VARCHAR(255) DEFAULT NULL);

CREATE TABLE IF NOT EXISTS soil_tests ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "test_date" DATE NOT NULL, "test_type" VARCHAR(100) DEFAULT NULL, "testing_lab" VARCHAR(255) DEFAULT NULL, "lab_report_url" VARCHAR(500) DEFAULT NULL, "soil_type" VARCHAR(50) DEFAULT NULL, "soil_texture" VARCHAR(50) DEFAULT NULL, "soil_color" VARCHAR(50) DEFAULT NULL, "ph_level" DECIMAL(3,1) NOT NULL, "electrical_conductivity" DECIMAL(6,2) DEFAULT NULL, "organic_carbon" DECIMAL(5,2) DEFAULT NULL, "organic_matter" DECIMAL(5,2) DEFAULT NULL, "nitrogen_n" DECIMAL(8,2) DEFAULT NULL, "phosphorus_p" DECIMAL(8,2) DEFAULT NULL, "potassium_k" DECIMAL(8,2) DEFAULT NULL, "calcium_ca" DECIMAL(8,2) DEFAULT NULL, "magnesium_mg" DECIMAL(8,2) DEFAULT NULL, "sulfur_s" DECIMAL(8,2) DEFAULT NULL, "iron_fe" DECIMAL(8,2) DEFAULT NULL, "manganese_mn" DECIMAL(8,2) DEFAULT NULL, "zinc_zn" DECIMAL(8,2) DEFAULT NULL, "copper_cu" DECIMAL(8,2) DEFAULT NULL, "boron_b" DECIMAL(8,2) DEFAULT NULL, "molybdenum_mo" DECIMAL(8,2) DEFAULT NULL, "nitrogen_status" VARCHAR(20) DEFAULT NULL, "phosphorus_status" VARCHAR(20) DEFAULT NULL, "potassium_status" VARCHAR(20) DEFAULT NULL, "water_holding_capacity" DECIMAL(5,2) DEFAULT NULL, "drainage_quality" VARCHAR(50) DEFAULT NULL, "bulk_density" DECIMAL(5,2) DEFAULT NULL, "porosity" DECIMAL(5,2) DEFAULT NULL, "microbial_activity" VARCHAR(50) DEFAULT NULL, "earthworm_count" INTEGER DEFAULT NULL, "overall_health_score" DECIMAL(3,2) DEFAULT NULL, "fertility_rating" VARCHAR(20) DEFAULT NULL, "lab_recommendations" TEXT DEFAULT NULL, "fertilizer_recommendations" JSONB DEFAULT NULL, "amendment_recommendations" JSONB DEFAULT NULL, "test_cost" DECIMAL(10,2) DEFAULT NULL, "plot_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS soil_test_results ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "test_date" TIMESTAMP NOT NULL, "lab_name" VARCHAR(255) DEFAULT NULL, "lab_reference_number" VARCHAR(255) DEFAULT NULL, "nitrogen_kg_per_ha" DECIMAL(10,2) DEFAULT NULL, "phosphorus_kg_per_ha" DECIMAL(10,2) DEFAULT NULL, "potassium_kg_per_ha" DECIMAL(10,2) DEFAULT NULL, "ph_level" DECIMAL(4,2) DEFAULT NULL, "organic_carbon_percent" DECIMAL(5,2) DEFAULT NULL, "organic_matter_percent" DECIMAL(5,2) DEFAULT NULL, "electrical_conductivity" DECIMAL(6,2) DEFAULT NULL, "sulfur_ppm" DECIMAL(10,2) DEFAULT NULL, "zinc_ppm" DECIMAL(10,2) DEFAULT NULL, "iron_ppm" DECIMAL(10,2) DEFAULT NULL, "manganese_ppm" DECIMAL(10,2) DEFAULT NULL, "copper_ppm" DECIMAL(10,2) DEFAULT NULL, "boron_ppm" DECIMAL(10,2) DEFAULT NULL, "soil_health_score" DECIMAL(5,2) DEFAULT NULL, "test_method" VARCHAR(255) DEFAULT NULL, "raw_data_json" TEXT DEFAULT NULL, "recommendations" TEXT DEFAULT NULL, "notes" TEXT DEFAULT NULL, "farm_id" BIGINT NOT NULL, "plot_id" BIGINT DEFAULT NULL);

CREATE TABLE IF NOT EXISTS supply_matches ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "matched_quantity" DECIMAL(10,2) NOT NULL, "match_score" DECIMAL(5,2) DEFAULT NULL, "price_offered" DECIMAL(10,2) DEFAULT NULL, "status" VARCHAR(50) NOT NULL DEFAULT 'suggested', "match_explanation" TEXT DEFAULT NULL, "is_aggregated" SMALLINT NOT NULL DEFAULT 0, "aggregation_group_id" VARCHAR(100) DEFAULT NULL, "farmer_confirmation_status" VARCHAR(50) NOT NULL DEFAULT 'pending', "farmer_confirmed_at" TIMESTAMP DEFAULT NULL, "buyer_accepted_at" TIMESTAMP DEFAULT NULL, "delivery_status" VARCHAR(50) NOT NULL DEFAULT 'pending', "delivery_notes" TEXT DEFAULT NULL, "request_id" BIGINT NOT NULL, "listing_id" BIGINT DEFAULT NULL, "farmer_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS supply_requests ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "crop_type" VARCHAR(100) NOT NULL, "quantity_needed" DECIMAL(10,2) NOT NULL, "quality_requirements" TEXT DEFAULT NULL, "delivery_date_start" TIMESTAMP NOT NULL, "delivery_date_end" TIMESTAMP NOT NULL, "max_price_per_unit" DECIMAL(10,2) DEFAULT NULL, "recurring" SMALLINT NOT NULL DEFAULT 0, "recurrence_pattern" TEXT DEFAULT NULL, "is_emergency" SMALLINT NOT NULL DEFAULT 0, "status" VARCHAR(50) NOT NULL DEFAULT 'open', "delivery_address" TEXT DEFAULT NULL, "delivery_latitude" DECIMAL(10,8) DEFAULT NULL, "delivery_longitude" DECIMAL(11,8) DEFAULT NULL, "delivery_pincode" VARCHAR(10) DEFAULT NULL, "delivery_state" VARCHAR(100) DEFAULT NULL, "delivery_district" VARCHAR(100) DEFAULT NULL, "notes" TEXT DEFAULT NULL, "embedding" vector(384) DEFAULT NULL, "embedding_cache_key" VARCHAR(255) DEFAULT NULL, "buyer_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS system_settings ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "key" VARCHAR(255) NOT NULL UNIQUE, "value" TEXT NOT NULL, "description" TEXT DEFAULT NULL);

CREATE TABLE IF NOT EXISTS transport_bookings ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "pickup_address" TEXT NOT NULL, "pickup_latitude" DECIMAL(10,8) DEFAULT NULL, "pickup_longitude" DECIMAL(11,8) DEFAULT NULL, "delivery_address" TEXT NOT NULL, "delivery_latitude" DECIMAL(10,8) DEFAULT NULL, "delivery_longitude" DECIMAL(11,8) DEFAULT NULL, "distance_km" DECIMAL(10,2) NOT NULL, "livestock_type" VARCHAR(100) NOT NULL, "livestock_count" INTEGER NOT NULL, "animal_value" DECIMAL(12,2) NOT NULL, "transport_cost" DECIMAL(10,2) NOT NULL, "insurance_opted" SMALLINT DEFAULT 0, "insurance_cost" DECIMAL(10,2) DEFAULT NULL, "total_cost" DECIMAL(10,2) NOT NULL, "scheduled_pickup_date" TIMESTAMP NOT NULL, "estimated_delivery_date" TIMESTAMP NOT NULL, "actual_pickup_date" TIMESTAMP DEFAULT NULL, "actual_delivery_date" TIMESTAMP DEFAULT NULL, "status" VARCHAR(50) DEFAULT 'pending', "tracking_updates" TEXT DEFAULT NULL, "special_instructions" TEXT DEFAULT NULL, "rating" INTEGER DEFAULT NULL, "review" TEXT DEFAULT NULL, "reviewed_at" TIMESTAMP DEFAULT NULL, "cancelled_at" TIMESTAMP DEFAULT NULL, "cancellation_reason" TEXT DEFAULT NULL, "transaction_id" BIGINT NOT NULL, "provider_id" BIGINT NOT NULL, "requester_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS transport_providers ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "company_name" VARCHAR(255) NOT NULL, "contact_person" VARCHAR(255) NOT NULL, "contact_phone" VARCHAR(20) NOT NULL, "contact_email" VARCHAR(255) DEFAULT NULL, "service_areas" TEXT NOT NULL, "vehicle_types" TEXT NOT NULL, "livestock_specialization" TEXT DEFAULT NULL, "base_rate_per_km" DECIMAL(10,2) NOT NULL, "minimum_charge" DECIMAL(10,2) NOT NULL, "insurance_available" SMALLINT DEFAULT 0, "insurance_rate_percentage" DECIMAL(5,2) DEFAULT NULL, "max_capacity_animals" INTEGER NOT NULL, "rating" DECIMAL(3,2) DEFAULT 0, "total_ratings" INTEGER DEFAULT 0, "completed_transports" INTEGER DEFAULT 0, "verified" SMALLINT DEFAULT 0, "verification_documents" TEXT DEFAULT NULL, "license_number" VARCHAR(100) DEFAULT NULL, "status" VARCHAR(50) DEFAULT 'active', "user_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS users ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "cognito_user_id" VARCHAR(255) DEFAULT NULL UNIQUE, "firebase_id" VARCHAR(255) DEFAULT NULL UNIQUE, "username" VARCHAR(100) NOT NULL, "name" VARCHAR(255) NOT NULL, "email" VARCHAR(255) DEFAULT NULL UNIQUE, "phone" VARCHAR(255) DEFAULT NULL UNIQUE, "google_id" VARCHAR(255) DEFAULT NULL, "facebook_id" VARCHAR(255) DEFAULT NULL, "password" VARCHAR(255) DEFAULT NULL, "user_type" VARCHAR(255) DEFAULT 'farmer', "preferred_language" VARCHAR(255) DEFAULT 'en', "mfa_enabled" SMALLINT DEFAULT 0, "latitude" DECIMAL(10,8) DEFAULT NULL, "longitude" DECIMAL(11,8) DEFAULT NULL, "pincode" VARCHAR(10) DEFAULT NULL, "state" VARCHAR(100) DEFAULT NULL, "district" VARCHAR(100) DEFAULT NULL, "village" VARCHAR(100) DEFAULT NULL, "address_line" VARCHAR(255) DEFAULT NULL, "is_active" SMALLINT DEFAULT 1, "is_verified" SMALLINT DEFAULT 0);

CREATE TABLE IF NOT EXISTS user_notifications ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "title" VARCHAR(255) NOT NULL, "message" TEXT NOT NULL, "type" VARCHAR(50) NOT NULL DEFAULT 'info', "link" VARCHAR(512) DEFAULT NULL, "data" JSONB DEFAULT NULL, "is_read" BOOLEAN NOT NULL DEFAULT false, "read_at" TIMESTAMP DEFAULT NULL, "user_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS veterinarians ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "added_by_user_id" BIGINT DEFAULT NULL, "name" VARCHAR(255) NOT NULL, "clinic_name" VARCHAR(255) DEFAULT NULL, "specialization" VARCHAR(100) DEFAULT NULL, "species_supported" TEXT DEFAULT NULL, "phone" VARCHAR(20) NOT NULL, "whatsapp" VARCHAR(20) DEFAULT NULL, "email" VARCHAR(255) DEFAULT NULL, "location_state" VARCHAR(100) DEFAULT NULL, "location_district" VARCHAR(100) DEFAULT NULL, "address" TEXT DEFAULT NULL, "available_now" SMALLINT NOT NULL DEFAULT 1, "verified" SMALLINT NOT NULL DEFAULT 0, "rating" DECIMAL(3,2) DEFAULT 0, "total_ratings" INTEGER DEFAULT 0, "notes" TEXT DEFAULT NULL);

CREATE TABLE IF NOT EXISTS voice_assist_logs ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "source" VARCHAR(20) NOT NULL DEFAULT 'text', "task" VARCHAR(50) DEFAULT NULL, "ui_lang" VARCHAR(10) DEFAULT NULL, "language_detected" VARCHAR(10) DEFAULT NULL, "mime_type" VARCHAR(50) DEFAULT NULL, "audio_bytes" INTEGER DEFAULT NULL, "duration_ms" INTEGER DEFAULT NULL, "transcript" TEXT DEFAULT NULL, "intent" VARCHAR(20) DEFAULT NULL, "model_used" VARCHAR(100) DEFAULT NULL, "status" VARCHAR(20) NOT NULL DEFAULT 'ok', "error" TEXT DEFAULT NULL, "latency_ms" INTEGER DEFAULT NULL, "user_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS weather_alerts ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "state" VARCHAR(255) NOT NULL, "district" VARCHAR(255) DEFAULT NULL, "alert_type" VARCHAR(255) NOT NULL, "severity" VARCHAR(255) NOT NULL, "message" TEXT NOT NULL, "recommendation" TEXT DEFAULT NULL, "valid_from" TIMESTAMP NOT NULL, "valid_until" TIMESTAMP NOT NULL, "is_active" SMALLINT DEFAULT 1, "farm_id" BIGINT DEFAULT NULL);

CREATE TABLE IF NOT EXISTS weather_forecasts ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "latitude" DECIMAL(10,8) NOT NULL, "longitude" DECIMAL(11,8) NOT NULL, "location_name" VARCHAR(255) DEFAULT NULL, "state" VARCHAR(100) DEFAULT NULL, "district" VARCHAR(100) DEFAULT NULL, "forecast_date" DATE NOT NULL, "forecast_time" TIMESTAMP DEFAULT NULL, "forecast_type" VARCHAR(50) DEFAULT NULL, "temperature_min" DECIMAL(5,2) DEFAULT NULL, "temperature_max" DECIMAL(5,2) DEFAULT NULL, "temperature_avg" DECIMAL(5,2) DEFAULT NULL, "feels_like" DECIMAL(5,2) DEFAULT NULL, "rainfall_probability" DECIMAL(5,2) DEFAULT NULL, "rainfall_amount" DECIMAL(8,2) DEFAULT NULL, "rainfall_intensity" VARCHAR(50) DEFAULT NULL, "wind_speed" DECIMAL(6,2) DEFAULT NULL, "wind_direction" VARCHAR(50) DEFAULT NULL, "wind_gust" DECIMAL(6,2) DEFAULT NULL, "humidity" DECIMAL(5,2) DEFAULT NULL, "pressure" DECIMAL(8,2) DEFAULT NULL, "dew_point" DECIMAL(5,2) DEFAULT NULL, "cloud_cover" DECIMAL(5,2) DEFAULT NULL, "visibility" DECIMAL(6,2) DEFAULT NULL, "uv_index" DECIMAL(4,2) DEFAULT NULL, "solar_radiation" DECIMAL(8,2) DEFAULT NULL, "weather_condition" VARCHAR(100) DEFAULT NULL, "weather_description" TEXT DEFAULT NULL, "weather_icon" VARCHAR(50) DEFAULT NULL, "evapotranspiration" DECIMAL(6,2) DEFAULT NULL, "soil_moisture_index" DECIMAL(5,2) DEFAULT NULL, "growing_degree_days" DECIMAL(6,2) DEFAULT NULL, "data_source" VARCHAR(100) DEFAULT NULL, "source_forecast_id" VARCHAR(255) DEFAULT NULL, "data_quality_score" DECIMAL(3,2) DEFAULT NULL, "fetched_at" TIMESTAMP DEFAULT NULL, "expires_at" TIMESTAMP DEFAULT NULL);

-- Foreign Keys

ALTER TABLE active_roles ADD CONSTRAINT active_role_user_id_foreign FOREIGN KEY ("user_id") REFERENCES users ("id");
ALTER TABLE active_roles ADD CONSTRAINT active_role_role_id_foreign FOREIGN KEY ("role_id") REFERENCES roles ("id");

ALTER TABLE advance_bookings ADD CONSTRAINT advance_booking_listing_id_foreign FOREIGN KEY ("listing_id") REFERENCES marketplace_listings ("id");
ALTER TABLE advance_bookings ADD CONSTRAINT advance_booking_buyer_id_foreign FOREIGN KEY ("buyer_id") REFERENCES users ("id");
ALTER TABLE advance_bookings ADD CONSTRAINT advance_booking_farmer_id_foreign FOREIGN KEY ("farmer_id") REFERENCES users ("id");

ALTER TABLE ai_usage_quota ADD CONSTRAINT ai_usage_quota_user_id_foreign FOREIGN KEY ("user_id") REFERENCES users ("id");

ALTER TABLE annual_strategies ADD CONSTRAINT annual_strategy_farm_id_foreign FOREIGN KEY ("farm_id") REFERENCES farms ("id");
ALTER TABLE annual_strategies ADD CONSTRAINT annual_strategy_farmer_id_foreign FOREIGN KEY ("farmer_id") REFERENCES users ("id");

ALTER TABLE breeding_records ADD CONSTRAINT breeding_record_livestock_id_foreign FOREIGN KEY ("livestock_id") REFERENCES livestock ("id");
ALTER TABLE breeding_records ADD CONSTRAINT breeding_record_farmer_id_foreign FOREIGN KEY ("farmer_id") REFERENCES users ("id");
ALTER TABLE breeding_records ADD CONSTRAINT breeding_record_mate_id_foreign FOREIGN KEY ("mate_id") REFERENCES livestock ("id");

ALTER TABLE buyer_interests ADD CONSTRAINT buyer_interest_listing_id_foreign FOREIGN KEY ("listing_id") REFERENCES marketplace_listings ("id");

ALTER TABLE crops ADD CONSTRAINT crop_farm_plot_id_foreign FOREIGN KEY ("farm_plot_id") REFERENCES farm_plots ("id");
ALTER TABLE crops ADD CONSTRAINT crop_strategy_id_foreign FOREIGN KEY ("strategy_id") REFERENCES annual_strategies ("id");

ALTER TABLE crop_diagnoses ADD CONSTRAINT crop_diagnosis_user_id_foreign FOREIGN KEY ("user_id") REFERENCES users ("id");

ALTER TABLE crop_expenses ADD CONSTRAINT crop_expense_crop_id_foreign FOREIGN KEY ("crop_id") REFERENCES crops ("id");

ALTER TABLE crop_milestones ADD CONSTRAINT crop_milestone_crop_id_foreign FOREIGN KEY ("crop_id") REFERENCES crops ("id");

ALTER TABLE farms ADD CONSTRAINT farm_user_id_foreign FOREIGN KEY ("user_id") REFERENCES users ("id");
ALTER TABLE farms ADD CONSTRAINT farm_owner_id_foreign FOREIGN KEY ("owner_id") REFERENCES users ("id");

ALTER TABLE farm_plots ADD CONSTRAINT farm_plot_farm_id_foreign FOREIGN KEY ("farm_id") REFERENCES farms ("id");

ALTER TABLE fertilizer_applications ADD CONSTRAINT fertilizer_application_farm_id_foreign FOREIGN KEY ("farm_id") REFERENCES farms ("id");
ALTER TABLE fertilizer_applications ADD CONSTRAINT fertilizer_application_plot_id_foreign FOREIGN KEY ("plot_id") REFERENCES farm_plots ("id");
ALTER TABLE fertilizer_applications ADD CONSTRAINT fertilizer_application_crop_id_foreign FOREIGN KEY ("crop_id") REFERENCES crops ("id");
ALTER TABLE fertilizer_applications ADD CONSTRAINT fertilizer_application_soil_test_before_id_foreign FOREIGN KEY ("soil_test_before_id") REFERENCES soil_test_results ("id");
ALTER TABLE fertilizer_applications ADD CONSTRAINT fertilizer_application_soil_test_after_id_foreign FOREIGN KEY ("soil_test_after_id") REFERENCES soil_test_results ("id");

ALTER TABLE livestock ADD CONSTRAINT livestock_farm_id_foreign FOREIGN KEY ("farm_id") REFERENCES farms ("id");
ALTER TABLE livestock ADD CONSTRAINT livestock_farmer_id_foreign FOREIGN KEY ("farmer_id") REFERENCES users ("id");

ALTER TABLE livestock_health_records ADD CONSTRAINT livestock_health_record_livestock_id_foreign FOREIGN KEY ("livestock_id") REFERENCES livestock ("id");

ALTER TABLE livestock_listings ADD CONSTRAINT livestock_listing_livestock_id_foreign FOREIGN KEY ("livestock_id") REFERENCES livestock ("id");
ALTER TABLE livestock_listings ADD CONSTRAINT livestock_listing_farmer_id_foreign FOREIGN KEY ("farmer_id") REFERENCES users ("id");

ALTER TABLE livestock_marketplace_listings ADD CONSTRAINT livestock_marketplace_listing_livestock_id_foreign FOREIGN KEY ("livestock_id") REFERENCES livestock ("id");
ALTER TABLE livestock_marketplace_listings ADD CONSTRAINT livestock_marketplace_listing_farmer_id_foreign FOREIGN KEY ("farmer_id") REFERENCES users ("id");

ALTER TABLE livestock_roi_predictions ADD CONSTRAINT livestock_roi_prediction_animal_id_foreign FOREIGN KEY ("animal_id") REFERENCES livestock ("id");
ALTER TABLE livestock_roi_predictions ADD CONSTRAINT livestock_roi_prediction_user_id_foreign FOREIGN KEY ("user_id") REFERENCES users ("id");

ALTER TABLE livestock_transactions ADD CONSTRAINT livestock_transaction_listing_id_foreign FOREIGN KEY ("listing_id") REFERENCES livestock_listings ("id");
ALTER TABLE livestock_transactions ADD CONSTRAINT livestock_transaction_seller_id_foreign FOREIGN KEY ("seller_id") REFERENCES users ("id");
ALTER TABLE livestock_transactions ADD CONSTRAINT livestock_transaction_buyer_id_foreign FOREIGN KEY ("buyer_id") REFERENCES users ("id");

ALTER TABLE market_prices ADD CONSTRAINT market_price_listing_id_foreign FOREIGN KEY ("listing_id") REFERENCES marketplace_listings ("id");
ALTER TABLE market_prices ADD CONSTRAINT market_price_booking_id_foreign FOREIGN KEY ("booking_id") REFERENCES advance_bookings ("id");
ALTER TABLE market_prices ADD CONSTRAINT market_price_transaction_id_foreign FOREIGN KEY ("transaction_id") REFERENCES livestock_transactions ("id");

ALTER TABLE marketplace_listings ADD CONSTRAINT marketplace_listing_farm_id_foreign FOREIGN KEY ("farm_id") REFERENCES farms ("id");
ALTER TABLE marketplace_listings ADD CONSTRAINT marketplace_listing_farmer_id_foreign FOREIGN KEY ("farmer_id") REFERENCES users ("id");

ALTER TABLE offspring ADD CONSTRAINT offspring_breeding_record_id_foreign FOREIGN KEY ("breeding_record_id") REFERENCES breeding_records ("id");
ALTER TABLE offspring ADD CONSTRAINT offspring_livestock_id_foreign FOREIGN KEY ("livestock_id") REFERENCES livestock ("id");
ALTER TABLE offspring ADD CONSTRAINT offspring_farmer_id_foreign FOREIGN KEY ("farmer_id") REFERENCES users ("id");

ALTER TABLE payment_milestones ADD CONSTRAINT payment_milestone_booking_id_foreign FOREIGN KEY ("booking_id") REFERENCES advance_bookings ("id");

ALTER TABLE pest_disease_alerts ADD CONSTRAINT pest_disease_alert_crop_id_foreign FOREIGN KEY ("crop_id") REFERENCES crops ("id");
ALTER TABLE pest_disease_alerts ADD CONSTRAINT pest_disease_alert_farm_id_foreign FOREIGN KEY ("farm_id") REFERENCES farms ("id");

ALTER TABLE quality_verifications ADD CONSTRAINT quality_verification_booking_id_foreign FOREIGN KEY ("booking_id") REFERENCES advance_bookings ("id");

ALTER TABLE satellite_observations ADD CONSTRAINT satellite_observation_farm_id_foreign FOREIGN KEY ("farm_id") REFERENCES farms ("id");

ALTER TABLE soil_amendments ADD CONSTRAINT soil_amendment_plot_id_foreign FOREIGN KEY ("plot_id") REFERENCES farm_plots ("id");
ALTER TABLE soil_amendments ADD CONSTRAINT soil_amendment_follow_up_soil_test_id_foreign FOREIGN KEY ("follow_up_soil_test_id") REFERENCES soil_tests ("id");

ALTER TABLE soil_tests ADD CONSTRAINT soil_test_plot_id_foreign FOREIGN KEY ("plot_id") REFERENCES farm_plots ("id");

ALTER TABLE soil_test_results ADD CONSTRAINT soil_test_result_farm_id_foreign FOREIGN KEY ("farm_id") REFERENCES farms ("id");
ALTER TABLE soil_test_results ADD CONSTRAINT soil_test_result_plot_id_foreign FOREIGN KEY ("plot_id") REFERENCES farm_plots ("id");

ALTER TABLE supply_matches ADD CONSTRAINT supply_match_request_id_foreign FOREIGN KEY ("request_id") REFERENCES supply_requests ("id");
ALTER TABLE supply_matches ADD CONSTRAINT supply_match_listing_id_foreign FOREIGN KEY ("listing_id") REFERENCES marketplace_listings ("id");
ALTER TABLE supply_matches ADD CONSTRAINT supply_match_farmer_id_foreign FOREIGN KEY ("farmer_id") REFERENCES users ("id");

ALTER TABLE supply_requests ADD CONSTRAINT supply_request_buyer_id_foreign FOREIGN KEY ("buyer_id") REFERENCES users ("id");

ALTER TABLE transport_bookings ADD CONSTRAINT transport_booking_transaction_id_foreign FOREIGN KEY ("transaction_id") REFERENCES livestock_transactions ("id");
ALTER TABLE transport_bookings ADD CONSTRAINT transport_booking_provider_id_foreign FOREIGN KEY ("provider_id") REFERENCES transport_providers ("id");
ALTER TABLE transport_bookings ADD CONSTRAINT transport_booking_requester_id_foreign FOREIGN KEY ("requester_id") REFERENCES users ("id");

ALTER TABLE transport_providers ADD CONSTRAINT transport_provider_user_id_foreign FOREIGN KEY ("user_id") REFERENCES users ("id");

ALTER TABLE user_notifications ADD CONSTRAINT user_notification_user_id_foreign FOREIGN KEY ("user_id") REFERENCES users ("id");

ALTER TABLE voice_assist_logs ADD CONSTRAINT voice_assist_log_user_id_foreign FOREIGN KEY ("user_id") REFERENCES users ("id");

ALTER TABLE weather_alerts ADD CONSTRAINT weather_alert_farm_id_foreign FOREIGN KEY ("farm_id") REFERENCES farms ("id");

-- Inserts

INSERT INTO roles (name) VALUES ('service_provider'),('isuper');