// Auto-generated TypeScript helper for API Registry
// Generated by scripts/generate_api_registry_simple.py

import apiRegistry from './api-registry.json';

export type ApiEndpoints = typeof apiRegistry.endpoints;

// Helper function to build URL with parameters
export function buildApiUrl(
  endpoint: string,
  params?: Record<string, string | number>
): string {
  let url = endpoint;
  
  if (params) {
    for (const [key, value] of Object.entries(params)) {
      url = url.replace(`{${key}}`, String(value));
    }
  }
  
  // Return just the path - api-client will prepend baseURL
  return url;
}

// Helper to get endpoint by category and name
export function getEndpoint(
  category: keyof ApiEndpoints,
  name: string
): string {
  const endpoints = apiRegistry.endpoints[category] as Record<string, string>;
  if (!endpoints || !endpoints[name]) {
    throw new Error(`Endpoint not found: ${category}.${name}`);
  }
  return endpoints[name];
}

// Helper to build full URL by category and name
export function buildUrl(
  category: keyof ApiEndpoints,
  name: string,
  params?: Record<string, string | number>
): string {
  const endpoint = getEndpoint(category, name);
  return buildApiUrl(endpoint, params);
}

// Export the registry
export { apiRegistry };
export default apiRegistry;
