import { Component, For, Show } from "solid-js";
import { A, useParams } from "@solidjs/router";

// Plan generated by POST /annual-strategy on the request page, kept for this visit (key: farm id)
interface Season {
  recommended_crop: string;
  variety?: string;
  expected_yield_per_acre?: string;
  expected_profit_per_acre?: number;
  investment_per_acre?: number;
  planting_window?: string;
  harvest_window?: string;
  key_success_factors?: string[];
  confidence_score?: number;
}

interface Plan {
  farm_id: number;
  farm_name: string;
  location: string;
  kharif: Season;
  rabi: Season;
  zaid?: Season | null;
  annual_summary: {
    total_expected_profit_per_acre?: number;
    total_investment_per_acre?: number;
    roi_percentage?: number;
    risk_level?: string;
    sustainability_score?: number;
  };
  alternative_options?: { season: string; crop: string; profit_difference?: number; risk_comparison?: string }[];
  monthly_action_plan?: { month: string; actions: string[] }[];
  generated_at: string;
  is_fallback?: boolean;
  regenerative_practices?: { practice: string; season?: string; why?: string; data_used?: string }[];
}

const rupees = (n?: number) => (n == null ? "—" : `₹${Math.round(n).toLocaleString("en-IN")}`);

const readPlan = (farmId: string): Plan | null => {
  try {
    return JSON.parse(sessionStorage.getItem(`strategy:${farmId}`) || "null");
  } catch {
    return null;
  }
};

const SEASONS: { key: "kharif" | "rabi" | "zaid"; label: string; tone: string }[] = [
  { key: "kharif", label: "Kharif (monsoon)", tone: "bg-sky-50 border-sky-200 text-sky-800" },
  { key: "rabi", label: "Rabi (winter)", tone: "bg-emerald-50 border-emerald-200 text-emerald-800" },
  { key: "zaid", label: "Zaid (summer)", tone: "bg-amber-50 border-amber-200 text-amber-800" },
];

export const AnnualStrategyDetail: Component = () => {
  const params = useParams();
  const plan = () => readPlan(params.id ?? "");

  return (
    <div class="space-y-6 max-w-5xl mx-auto pb-20">
      <Show
        when={plan()}
        fallback={
          <div class="bg-white p-6 rounded-2xl border border-slate-200/80 shadow-sm space-y-3">
            <h1 class="text-xl font-black text-slate-900">Annual Crop Strategy</h1>
            <p class="text-sm text-slate-600">
              No plan generated for this farm yet. Choose a farm and budget, and our AI strategy engine builds a kharif, rabi and zaid
              plan from its soil and district weather.
            </p>
            <A
              href={params.id ? `/strategy/request?farmId=${params.id}` : "/strategy/select-farm"}
              class="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-forest text-white text-sm font-bold"
            >
              <span class="material-symbols-outlined text-base">auto_awesome</span>
              Generate a plan
            </A>
          </div>
        }
      >
        {(p) => (
          <>
            <div class="bg-white p-5 rounded-2xl border border-slate-200/80 shadow-sm flex flex-wrap items-center justify-between gap-3">
              <div>
                <div class="flex items-center gap-2 flex-wrap">
                  <h1 class="text-xl md:text-2xl font-black text-slate-900 tracking-tight">Annual Crop Strategy</h1>
                  <span class="text-xs font-bold px-2 py-0.5 rounded-full bg-forest/10 text-forest">
                    {p().is_fallback ? "Generic regional plan" : "CropSense AI Engine"}
                  </span>
                </div>
                <p class="text-xs text-slate-500 mt-0.5">
                  {p().farm_name} &bull; {p().location} &bull; generated {new Date(p().generated_at).toLocaleString("en-IN")}
                </p>
              </div>
              <A
                href={`/strategy/request?farmId=${p().farm_id}`}
                class="px-4 py-2 rounded-xl border border-slate-200 text-xs font-semibold text-slate-700 hover:bg-slate-50"
              >
                Regenerate
              </A>
            </div>

            <Show when={p().is_fallback}>
              <div class="p-4 rounded-2xl bg-amber-50 border border-amber-200 text-sm text-amber-900">
                AI strategy service was temporarily unavailable, so this is a generic plan for the region, not specific advice for your field. Try
                regenerating in a few minutes.
              </div>
            </Show>

            <div class="grid grid-cols-1 md:grid-cols-3 gap-5">
              <div class="bg-white p-5 rounded-2xl border border-slate-200/80 shadow-sm text-center">
                <span class="text-[10px] text-slate-400 font-bold uppercase block">Expected profit / acre / year</span>
                <span class="text-2xl font-black text-emerald-700">{rupees(p().annual_summary.total_expected_profit_per_acre)}</span>
                <span class="text-xs text-slate-500 block">
                  on {rupees(p().annual_summary.total_investment_per_acre)} invested
                </span>
              </div>
              <div class="bg-white p-5 rounded-2xl border border-slate-200/80 shadow-sm text-center">
                <span class="text-[10px] text-slate-400 font-bold uppercase block">Return on investment</span>
                <span class="text-2xl font-black text-slate-900">
                  {p().annual_summary.roi_percentage != null ? `${Math.round(p().annual_summary.roi_percentage!)}%` : "—"}
                </span>
                <span class="text-xs text-slate-500 block capitalize">Risk: {p().annual_summary.risk_level || "—"}</span>
              </div>
              <div class="bg-white p-5 rounded-2xl border border-slate-200/80 shadow-sm text-center">
                <span class="text-[10px] text-slate-400 font-bold uppercase block">Sustainability score</span>
                <span class="text-2xl font-black text-forest">
                  {p().annual_summary.sustainability_score != null
                    ? `${Math.round(p().annual_summary.sustainability_score! * 100)}/100`
                    : "—"}
                </span>
                <span class="text-xs text-slate-500 block">Soil health, water use and rotation</span>
              </div>
            </div>

            <div class="bg-white p-6 rounded-2xl border border-slate-200/80 shadow-sm space-y-4">
              <h3 class="font-bold text-sm text-slate-900">3-Season Rotation</h3>
              <div class="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <For each={SEASONS.filter((s) => p()[s.key]?.recommended_crop)}>
                  {(season) => {
                    const s = () => p()[season.key] as Season;
                    return (
                      <div class={`p-4 rounded-xl border space-y-2 ${season.tone}`}>
                        <span class="text-[11px] font-bold uppercase">{season.label}</span>
                        <div class="text-base font-black text-slate-900">{s().recommended_crop}</div>
                        <Show when={s().variety}>
                          <div class="text-xs text-slate-600">Variety: {s().variety}</div>
                        </Show>
                        <div class="text-xs text-slate-600">
                          Sow {s().planting_window || "—"} &bull; Harvest {s().harvest_window || "—"}
                        </div>
                        <div class="text-xs text-slate-700">
                          Yield {s().expected_yield_per_acre || "—"} &bull; Profit {rupees(s().expected_profit_per_acre)}/acre
                          &bull; Cost {rupees(s().investment_per_acre)}/acre
                        </div>
                        <Show when={s().key_success_factors?.length}>
                          <ul class="list-disc pl-4 text-xs text-slate-600 space-y-1">
                            <For each={s().key_success_factors}>{(f) => <li>{f}</li>}</For>
                          </ul>
                        </Show>
                        <Show when={s().confidence_score != null}>
                          <div class="text-[10px] text-slate-500">Confidence {Math.round((s().confidence_score || 0) * 100)}%</div>
                        </Show>
                      </div>
                    );
                  }}
                </For>
              </div>
            </div>

            <Show when={p().regenerative_practices?.length}>
              <div class="bg-white p-6 rounded-2xl border border-emerald-200 shadow-sm space-y-3">
                <h3 class="font-bold text-sm text-slate-900 flex items-center gap-2">
                  <span class="material-symbols-outlined text-base text-forest">eco</span>
                  Regenerative practices for this field
                </h3>
                <For each={p().regenerative_practices}>
                  {(r) => (
                    <div class="text-xs border-t border-slate-100 pt-2 space-y-0.5">
                      <div>
                        <strong class="text-slate-900">{r.practice}</strong>
                        <Show when={r.season}>
                          <span class="ml-2 text-[10px] font-bold uppercase text-emerald-700">{r.season}</span>
                        </Show>
                      </div>
                      <Show when={r.why}>
                        <p class="text-slate-600">{r.why}</p>
                      </Show>
                      <Show when={r.data_used}>
                        <p class="text-[11px] text-slate-500">Based on: {r.data_used}</p>
                      </Show>
                    </div>
                  )}
                </For>
              </div>
            </Show>

            <Show when={p().alternative_options?.length}>
              <div class="bg-white p-6 rounded-2xl border border-slate-200/80 shadow-sm space-y-3">
                <h3 class="font-bold text-sm text-slate-900">Alternatives</h3>
                <For each={p().alternative_options}>
                  {(alt) => (
                    <div class="text-xs text-slate-700 border-t border-slate-100 pt-2">
                      <strong class="capitalize">{alt.season}:</strong> {alt.crop}
                      {alt.profit_difference != null && ` (${alt.profit_difference >= 0 ? "+" : ""}${rupees(alt.profit_difference)}/acre)`}
                      <Show when={alt.risk_comparison}>
                        <p class="text-slate-500 mt-0.5">{alt.risk_comparison}</p>
                      </Show>
                    </div>
                  )}
                </For>
              </div>
            </Show>

            <Show when={p().monthly_action_plan?.some((m) => m.actions?.length)}>
              <div class="bg-white p-6 rounded-2xl border border-slate-200/80 shadow-sm space-y-3">
                <h3 class="font-bold text-sm text-slate-900">Month-by-month actions</h3>
                <For each={p().monthly_action_plan?.filter((m) => m.actions?.length)}>
                  {(m) => (
                    <div class="text-xs border-t border-slate-100 pt-2">
                      <strong class="text-slate-900">{m.month}</strong>
                      <ul class="list-disc pl-4 text-slate-600 mt-1 space-y-0.5">
                        <For each={m.actions}>{(a) => <li>{a}</li>}</For>
                      </ul>
                    </div>
                  )}
                </For>
              </div>
            </Show>
          </>
        )}
      </Show>
    </div>
  );
};
