export interface Annual_strategy {
   id: number,
   created_at: Date,
   updated_at: Date,
   enable: number,
   year: number,
   kharif_crop: string | null,
   kharif_profit_estimate: number | null,
   kharif_confidence_score: number | null,
   rabi_crop: string | null,
   rabi_profit_estimate: number | null,
   rabi_confidence_score: number | null,
   zaid_crop: string | null,
   zaid_profit_estimate: number | null,
   zaid_confidence_score: number | null,
   total_annual_profit: number | null,
   implementation_timeline: string | null,
   alternative_options: string | null,
   risk_mitigation: string | null,
   bedrock_response: string | null,
   status: string | null,
   farm_id: number,
   farmer_id: number
}