export interface Crop_profitability {
   id: number,
   created_at: Date,
   updated_at: Date,
   enable: number,
   crop_type: string,
   variety: string | null,
   state: string,
   district: string | null,
   year: number,
   season: string | null,
   avg_profit_per_acre: number,
   min_profit_per_acre: number | null,
   max_profit_per_acre: number | null,
   seed_cost: number | null,
   fertilizer_cost: number | null,
   pesticide_cost: number | null,
   labor_cost: number | null,
   irrigation_cost: number | null,
   equipment_cost: number | null,
   other_costs: number | null,
   total_investment_cost: number | null,
   avg_revenue_per_acre: number | null,
   roi_percentage: number | null,
   break_even_yield: number | null,
   profit_margin: number | null,
   risk_level: string | null,
   price_risk_score: number | null,
   yield_risk_score: number | null,
   market_demand: string | null,
   competition_level: string | null,
   data_source: string | null,
   sample_size: number | null
}