export interface Farm {
   id: number,
   created_at: Date,
   updated_at: Date,
   enable: number,
   name: string,
   description: string | null,
   location_state: string,
   location_district: string,
   location_block: string | null,
   location_village: string | null,
   latitude: number | null,
   longitude: number | null,
   total_area: number,
   cultivable_area: number | null,
   area_unit: string | null,
   primary_soil_type: string | null,
   soil_ph: number | null,
   soil_characteristics: any | null,
   irrigation_type: string | null,
   water_availability: string | null,
   previous_crops: string[] | null,
   farming_experience_years: number | null,
   investment_capacity_per_acre: number | null,
   farm_profile_embedding: number[] | null,
   is_active: boolean | null,
   is_verified: boolean | null,
   nitrogen: number | null,
   phosphorus: number | null,
   potassium: number | null,
   ph_level: number | null,
   organic_carbon: number | null,
   electrical_conductivity: number | null,
   sulfur: number | null,
   zinc: number | null,
   iron: number | null,
   boron: number | null,
   copper: number | null,
   manganese: number | null,
   soil_depth_class: string | null,
   slope_class: string | null,
   erosion_class: string | null,
   soil_texture_class: string | null,
   land_capability_class: string | null,
   land_irrigability_class: string | null,
   hydrological_soil_group: string | null,
   shc_data_source: string | null,
   shc_fetched_at: Date | null,
   shc_partial_data: boolean | null,
   shc_unavailable_styles: string[] | null,
   user_id: number,
   owner_id: number
}