export interface Farm_plot {
   id: number,
   created_at: Date,
   updated_at: Date,
   enable: number,
   plot_name: string,
   area: number,
   soil_type: string,
   irrigation_type: string,
   state: string,
   district: string,
   previous_crops: string | null,
   investment_capacity: number | null,
   nitrogen: number | null,
   phosphorus: number | null,
   potassium: number | null,
   ph_level: number | null,
   organic_carbon: number | null,
   electrical_conductivity: number | null,
   sulfur: number | null,
   zinc: number | null,
   iron: number | null,
   boron: number | null,
   farm_id: number
}