export interface Fertilizer_application {
   id: number,
   created_at: Date,
   updated_at: Date,
   enable: number,
   application_date: Date,
   fertilizer_type: string,
   category: string,
   quantity_kg: number,
   quantity_per_hectare: number | null,
   area_applied_hectares: number | null,
   nitrogen_kg: number | null,
   phosphorus_kg: number | null,
   potassium_kg: number | null,
   cost_total: number | null,
   cost_per_kg: number | null,
   cost_per_hectare: number | null,
   application_method: string | null,
   growth_stage: string | null,
   days_after_planting: number | null,
   effectiveness_score: number | null,
   soil_response_notes: string | null,
   weather_conditions: string | null,
   temperature_celsius: number | null,
   rainfall_mm_24h: number | null,
   recommended_by: string | null,
   recommendation_id: string | null,
   notes: string | null,
   farm_id: number,
   plot_id: number | null,
   crop_id: number | null,
   soil_test_before_id: number | null,
   soil_test_after_id: number | null
}