export interface Historical_yield {
   id: number,
   created_at: Date,
   updated_at: Date,
   enable: number,
   crop_type: string,
   variety: string | null,
   state: string,
   district: string | null,
   block: string | null,
   year: number,
   season: string | null,
   avg_yield_per_acre: number,
   min_yield: number | null,
   max_yield: number | null,
   success_rate: number | null,
   farmer_count: number | null,
   total_area_cultivated: number | null,
   soil_types: any | null,
   irrigation_methods: any | null,
   avg_rainfall: number | null,
   avg_temperature: number | null,
   quality_distribution: any | null,
   avg_quality_grade: string | null,
   data_source: string | null,
   data_quality_score: number | null
}