export interface Livestock_transaction {
   id: number,
   created_at: Date,
   updated_at: Date,
   enable: number,
   transaction_type: string,
   quantity: number,
   agreed_price: number,
   status: string | null,
   buyer_message: string | null,
   seller_response: string | null,
   buyer_contact_phone: string | null,
   buyer_contact_email: string | null,
   delivery_required: boolean | null,
   delivery_address: string | null,
   delivery_latitude: number | null,
   delivery_longitude: number | null,
   health_guarantee_days: number | null,
   health_guarantee_expires: Date | null,
   completed_at: Date | null,
   cancelled_at: Date | null,
   cancellation_reason: string | null,
   notes: string | null,
   listing_id: number,
   seller_id: number,
   buyer_id: number
}