export interface Livestock {
   id: number,
   created_at: Date,
   updated_at: Date,
   enable: number,
   species: string,
   breed: string,
   name: string | null,
   quantity: number,
   purchase_price: number,
   purchase_date: Date,
   purpose: string,
   expected_roi: number | null,
   break_even_date: Date | null,
   status: string | null,
   latitude: number | null,
   longitude: number | null,
   pincode: string | null,
   state: string | null,
   district: string | null,
   village: string | null,
   address_line: string | null,
   farm_id: number,
   farmer_id: number
}