export interface Livestock_listing {
   id: number,
   created_at: Date,
   updated_at: Date,
   enable: number,
   title: string,
   description: string | null,
   species: string,
   breed: string,
   age_years: number | null,
   age_months: number | null,
   gender: string,
   quantity: number,
   purpose: string,
   price: number,
   price_negotiable: boolean | null,
   weight_kg: number | null,
   health_status: string | null,
   vaccination_status: string | null,
   last_vaccination_date: Date | null,
   milk_production_liters: number | null,
   breeding_certified: boolean | null,
   breeding_certification_number: string | null,
   genetic_lineage: string | null,
   photos: string | null,
   videos: string | null,
   location_state: string,
   location_district: string,
   location_village: string | null,
   latitude: number | null,
   longitude: number | null,
   pincode: string | null,
   address_line: string | null,
   farmer_contact_phone: string | null,
   farmer_contact_email: string | null,
   status: string | null,
   views_count: number | null,
   interest_count: number | null,
   inquiry_count: number | null,
   featured: boolean | null,
   featured_until: Date | null,
   livestock_id: number,
   farmer_id: number
}