export interface Livestock_marketplace_listing {
   id: number,
   created_at: Date,
   updated_at: Date,
   enable: number,
   listing_type: string,
   asking_price: number,
   current_age_months: number,
   current_weight_kg: number | null,
   milk_production_liters_per_day: number | null,
   breeding_history: string | null,
   health_status: string | null,
   vaccination_status: string | null,
   total_investment: number,
   total_revenue: number | null,
   current_roi_percentage: number | null,
   break_even_achieved: boolean | null,
   break_even_date: Date | null,
   projected_annual_profit: number | null,
   location_state: string,
   location_district: string,
   farmer_contact_phone: string,
   farmer_contact_email: string | null,
   listing_status: string | null,
   views_count: number | null,
   bedrock_analysis: string | null,
   livestock_id: number,
   farmer_id: number
}