export interface Marketplace_listing {
   id: number,
   created_at: Date,
   updated_at: Date,
   enable: number,
   crop_type: string,
   crop_variety: string | null,
   expected_harvest_date: Date,
   estimated_quantity: number,
   available_quantity: number | null,
   quality_grade: string | null,
   location_state: string,
   location_district: string,
   farmer_contact_phone: string | null,
   farmer_contact_email: string | null,
   status: string | null,
   delivery_latitude: number | null,
   delivery_longitude: number | null,
   delivery_pincode: string | null,
   delivery_village: string | null,
   delivery_address_line: string | null,
   embedding: string | null,
   embedding_cache_key: string | null,
   price_per_unit: number | null,
   farm_id: number,
   farmer_id: number
}