export interface Opportunity_cost {
   id: number,
   created_at: Date,
   updated_at: Date,
   enable: number,
   location_state: string,
   location_district: string | null,
   primary_crop: string,
   alternative_crop: string,
   season: string | null,
   year: number | null,
   primary_crop_profit: number,
   alternative_crop_profit: number,
   profit_difference: number,
   primary_crop_investment: number | null,
   alternative_crop_investment: number | null,
   investment_difference: number | null,
   primary_crop_roi: number | null,
   alternative_crop_roi: number | null,
   roi_difference: number | null,
   primary_crop_risk: string | null,
   alternative_crop_risk: string | null,
   risk_factor: number | null,
   primary_crop_demand: string | null,
   alternative_crop_demand: string | null,
   market_stability_comparison: string | null,
   recommended_choice: string | null,
   recommendation_confidence: number | null,
   recommendation_reasoning: string | null,
   soil_suitability_comparison: any | null,
   water_requirement_comparison: any | null,
   labor_requirement_comparison: any | null
}