export interface Pest_disease_data {
   id: number,
   created_at: Date,
   updated_at: Date,
   enable: number,
   name: string,
   type: string,
   scientific_name: string | null,
   description: string,
   affected_crops: string | null,
   risk_stages: string | null,
   temperature_min: number | null,
   temperature_max: number | null,
   humidity_min: number | null,
   humidity_max: number | null,
   rainfall_min: number | null,
   severity: string,
   organic_treatments: string | null,
   chemical_treatments: string | null,
   prevention_measures: string | null,
   timing_instructions: string | null,
   data_source: string | null,
   last_updated: Date | null
}