export interface Seasonal_trend {
   id: number,
   created_at: Date,
   updated_at: Date,
   enable: number,
   crop_type: string,
   state: string,
   district: string | null,
   planting_season: string,
   harvest_season: string | null,
   optimal_planting_start: Date | null,
   optimal_planting_end: Date | null,
   optimal_harvest_start: Date | null,
   optimal_harvest_end: Date | null,
   avg_growth_duration_days: number | null,
   price_trend_yoy: number | null,
   demand_trend_yoy: number | null,
   yield_trend_yoy: number | null,
   weather_suitability_score: number | null,
   pest_disease_risk: string | null,
   market_timing_score: number | null,
   avg_success_rate: number | null,
   farmer_adoption_rate: number | null,
   recommended_varieties: any | null,
   companion_crops: any | null,
   rotation_recommendations: any | null,
   analysis_start_year: number | null,
   analysis_end_year: number | null,
   years_of_data: number | null
}