export interface Slusi_lcc_report {
   id: number,
   created_at: Date,
   updated_at: Date,
   enable: number,
   state: string,
   district: string,
   report_no: string,
   year: number | null,
   total_area_ha: number | null,
   lcc_class_i: number | null,
   lcc_class_ii: number | null,
   lcc_class_iii: number | null,
   lcc_class_iv: number | null,
   lcc_class_v: number | null,
   lcc_class_vi: number | null,
   lcc_class_vii: number | null,
   lcc_class_viii: number | null,
   forest_area: number | null,
   miscellaneous_area: number | null,
   spatial_available: boolean | null,
   non_spatial_available: boolean | null,
   ingested_at: Date
}