export interface Soil_amendment {
   id: number,
   created_at: Date,
   updated_at: Date,
   enable: number,
   amendment_date: Date,
   amendment_type: string,
   amendment_name: string | null,
   primary_purpose: string | null,
   target_improvement: any | null,
   quantity: number,
   unit: string,
   quantity_per_acre: number | null,
   application_method: string | null,
   incorporation_depth: number | null,
   cost: number | null,
   cost_per_acre: number | null,
   organic_matter_content: number | null,
   nutrient_content: any | null,
   carbon_nitrogen_ratio: number | null,
   current_ph: number | null,
   target_ph: number | null,
   expected_ph_change: number | null,
   days_before_planting: number | null,
   soil_moisture_at_application: string | null,
   weather_conditions: any | null,
   expected_benefits: any | null,
   expected_duration_months: number | null,
   actual_benefits: any | null,
   effectiveness_rating: number | null,
   recommendation_source: string | null,
   recommended_by: string | null,
   notes: string | null,
   plot_id: number,
   follow_up_soil_test_id: number | null
}