export interface Soil_test {
   id: number,
   created_at: Date,
   updated_at: Date,
   enable: number,
   test_date: Date,
   test_type: string | null,
   testing_lab: string | null,
   lab_report_url: string | null,
   soil_type: string | null,
   soil_texture: string | null,
   soil_color: string | null,
   ph_level: number,
   electrical_conductivity: number | null,
   organic_carbon: number | null,
   organic_matter: number | null,
   nitrogen_n: number | null,
   phosphorus_p: number | null,
   potassium_k: number | null,
   calcium_ca: number | null,
   magnesium_mg: number | null,
   sulfur_s: number | null,
   iron_fe: number | null,
   manganese_mn: number | null,
   zinc_zn: number | null,
   copper_cu: number | null,
   boron_b: number | null,
   molybdenum_mo: number | null,
   nitrogen_status: string | null,
   phosphorus_status: string | null,
   potassium_status: string | null,
   water_holding_capacity: number | null,
   drainage_quality: string | null,
   bulk_density: number | null,
   porosity: number | null,
   microbial_activity: string | null,
   earthworm_count: number | null,
   overall_health_score: number | null,
   fertility_rating: string | null,
   lab_recommendations: string | null,
   fertilizer_recommendations: any | null,
   amendment_recommendations: any | null,
   test_cost: number | null,
   plot_id: number
}