export interface Supply_request {
   id: number,
   created_at: Date,
   updated_at: Date,
   enable: number,
   crop_type: string,
   quantity_needed: number,
   quality_requirements: string | null,
   delivery_date_start: Date,
   delivery_date_end: Date,
   max_price_per_unit: number | null,
   recurring: boolean,
   recurrence_pattern: string | null,
   is_emergency: boolean,
   status: string,
   delivery_address: string | null,
   delivery_latitude: number | null,
   delivery_longitude: number | null,
   delivery_pincode: string | null,
   delivery_state: string | null,
   delivery_district: string | null,
   notes: string | null,
   embedding: string | null,
   embedding_cache_key: string | null,
   buyer_id: number
}