export interface Transport_provider {
   id: number,
   created_at: Date,
   updated_at: Date,
   enable: number,
   company_name: string,
   contact_person: string,
   contact_phone: string,
   contact_email: string | null,
   service_areas: string,
   vehicle_types: string,
   livestock_specialization: string | null,
   base_rate_per_km: number,
   minimum_charge: number,
   insurance_available: boolean | null,
   insurance_rate_percentage: number | null,
   max_capacity_animals: number,
   rating: number | null,
   total_ratings: number | null,
   completed_transports: number | null,
   verified: boolean | null,
   verification_documents: string | null,
   license_number: string | null,
   status: string | null,
   user_id: number
}