export interface Weather_forecast {
   id: number,
   created_at: Date,
   updated_at: Date,
   enable: number,
   latitude: number,
   longitude: number,
   location_name: string | null,
   state: string | null,
   district: string | null,
   forecast_date: Date,
   forecast_time: Date | null,
   forecast_type: string | null,
   temperature_min: number | null,
   temperature_max: number | null,
   temperature_avg: number | null,
   feels_like: number | null,
   rainfall_probability: number | null,
   rainfall_amount: number | null,
   rainfall_intensity: string | null,
   wind_speed: number | null,
   wind_direction: string | null,
   wind_gust: number | null,
   humidity: number | null,
   pressure: number | null,
   dew_point: number | null,
   cloud_cover: number | null,
   visibility: number | null,
   uv_index: number | null,
   solar_radiation: number | null,
   weather_condition: string | null,
   weather_description: string | null,
   weather_icon: string | null,
   evapotranspiration: number | null,
   soil_moisture_index: number | null,
   growing_degree_days: number | null,
   data_source: string | null,
   source_forecast_id: string | null,
   data_quality_score: number | null,
   fetched_at: Date | null,
   expires_at: Date | null
}